version: "3.9"

services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: kh817012
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://fastapi_user:kh817012@db:5432/fastapi_db
  frontend:
    build:
      context: ./frontapp-react
    container_name: react
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontapp-react/src:/app/src